### ISSUE TITLE
cant scrape group members

### ISSUE THREAD

**Issue by baramhs** [Chustinjeng/Telegram-scraper-and-adder#2]
![Screenshot_37](https://user-images.githubusercontent.com/99220018/178189191-af77f4ac-3d3d-4135-9e8e-c77a137e3daf.jpg)

**Comment by x0Hy168** [comment]
Hi, you are getting "FloodWaitError", you are requesting for participant details too often. Telegram API have a limit of 50 request per day. Please wait another day for your account to cool down.
